package main

var testBlocks = []map[string]bool{
	{
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": false,
		"gym":    true,
		"store":  false,
	},
	{
		"school": true,
		"gym":    true,
		"store":  false,
	},
	{ // max distance: 1
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  true,
	},
}

var testBlocksLong = []map[string]bool{
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
}

var testBlocksWithZeroDistance = []map[string]bool{
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    true,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
	{
		"school": true,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": false,
		"gym":    true,
		"store":  false,
	}, {
		"school": false,
		"gym":    false,
		"store":  false,
	}, {
		"school": true,
		"gym":    false,
		"store":  true,
	}, {
		"school": true,
		"gym":    false,
		"store":  false,
	},
}
